<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'abstractship' => '/Models/AbstractShip.php',
                'board' => '/Models/Board.php',
                'carrier' => '/Models/Carrier.php',
                'destroyer' => '/Models/Destroyer.php',
                'gamelogic' => '/Logic/GameLogic.php',
                'greeter' => '/Greeter.php',
                'position' => '/Models/Position.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
